on:
    push:
        tags:
          - 'v*.*.*'

permissions:
    contents: read       # Required for actions/checkout

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Make stable release to npm
              uses: esamattis/npm-release@v2
              with:
                  type: stable
                  token: ${{ secrets.CAZOO_NPM_TOKEN }}
